-- ============================================================================
-- PKM Center Unila — Skema Database v2 (revisi struktur DB)
-- Target  : PostgreSQL 16 (docker image: postgres:16-alpine)
-- File    : backend/migrations/0001_init_pkm_schema.sql
-- Sumber  : ERD revisi "Digitalisasi Manajemen PKM" (lihat
--           docs/revisi-struktur-db-pkm-center.md untuk pemetaan & penjelasan)
--
-- Catatan:
--  * Dijalankan sebagai migrasi awal skema baru (idempoten via IF NOT EXISTS).
--  * Tabel lama (users/content/timelines/pedoman/portfolios/feedbacks/
--    scheme_stats/contact_infos) dipetakan ke tabel baru di dokumen desain.
--    Tabel content_media, feedbacks, contact_infos disediakan agar fitur lama
--    (video/galeri, masukan, kontak) tidak kehilangan wadah.
--  * Status/enum memakai varchar + CHECK (mudah dipetakan GORM). Nilai-nilai
--    yang diizinkan ada di masing-masing CHECK.
-- ============================================================================

BEGIN;

-- gen_random_uuid() sudah bawaan PostgreSQL 13+, ekstensi pgcrypto tetap
-- disiapkan untuk jaga-jaga pada instance lama.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================================
-- 1. AUTENTIKASI & PENGGUNA
-- ============================================================================

-- ROLES -----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL UNIQUE,   -- admin | mahasiswa | dosen | reviewer | ...
    name        VARCHAR(100) NOT NULL,
    description TEXT
);

-- USERS -----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email             VARCHAR(255) NOT NULL UNIQUE,
    password_hash     VARCHAR(255) NOT NULL,
    full_name         VARCHAR(255) NOT NULL,
    phone             VARCHAR(30),
    account_status    VARCHAR(30)  NOT NULL DEFAULT 'active'
                      CHECK (account_status IN ('active', 'pending', 'suspended', 'inactive')),
    auth_provider     VARCHAR(30)  NOT NULL DEFAULT 'local'
                      CHECK (auth_provider IN ('local', 'google', 'sso')),
    email_verified_at TIMESTAMPTZ,
    last_login_at     TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_users_account_status ON users (account_status);

-- USER_ROLES ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_roles (
    user_id     UUID   NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id     BIGINT NOT NULL REFERENCES roles (id) ON DELETE RESTRICT,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, role_id)
);
CREATE INDEX IF NOT EXISTS idx_user_roles_role_id ON user_roles (role_id);

-- STUDENT_PROFILES ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS student_profiles (
    user_id        UUID PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    student_number VARCHAR(30) NOT NULL UNIQUE,
    faculty        VARCHAR(120),
    department     VARCHAR(120),
    study_program  VARCHAR(120),
    entry_year     INT CHECK (entry_year BETWEEN 1900 AND 2100),
    gpa            NUMERIC(3, 2) CHECK (gpa >= 0 AND gpa <= 4),
    academic_status VARCHAR(30)
        CHECK (academic_status IN ('active', 'leave', 'graduated', 'dropout')),
    biography      TEXT
);

-- LECTURER_PROFILES -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS lecturer_profiles (
    user_id              UUID PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    lecturer_number      VARCHAR(30) NOT NULL UNIQUE,
    faculty              VARCHAR(120),
    department           VARCHAR(120),
    study_program        VARCHAR(120),
    academic_position    VARCHAR(120),  -- Asisten Ahli, Lektor, Lektor Kepala, Guru Besar
    biography            TEXT,
    supervision_capacity INT CHECK (supervision_capacity >= 0)
);

-- EXPERTISE_FIELDS ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS expertise_fields (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL UNIQUE,
    description TEXT
);

-- USER_EXPERTISE --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_expertise (
    user_id         UUID   NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    expertise_id    BIGINT NOT NULL REFERENCES expertise_fields (id) ON DELETE CASCADE,
    expertise_level VARCHAR(30)
        CHECK (expertise_level IN ('beginner', 'intermediate', 'advanced', 'expert')),
    PRIMARY KEY (user_id, expertise_id)
);
CREATE INDEX IF NOT EXISTS idx_user_expertise_expertise_id ON user_expertise (expertise_id);

-- ACHIEVEMENTS ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS achievements (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id          UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title               VARCHAR(255) NOT NULL,
    category            VARCHAR(100),
    organizer           VARCHAR(255),
    achievement_level   VARCHAR(50)  -- universitas | nasional | internasional
        CHECK (achievement_level IN ('fakultas', 'universitas', 'regional', 'nasional', 'internasional')),
    "rank"              VARCHAR(100),
    achievement_date    DATE,
    certificate_url     TEXT,
    verification_status VARCHAR(30) NOT NULL DEFAULT 'pending'
        CHECK (verification_status IN ('pending', 'verified', 'rejected')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_achievements_student_id ON achievements (student_id);

-- ============================================================================
-- 2. MASTER PKM: PERIODE, SKEMA, TAHAPAN
-- ============================================================================

-- PKM_PERIODS -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pkm_periods (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name               VARCHAR(150) NOT NULL,
    year               INT NOT NULL CHECK (year BETWEEN 1900 AND 2100),
    registration_start DATE,
    registration_end   DATE,
    status             VARCHAR(30) NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'open', 'closed', 'archived')),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (year, name)
);
CREATE INDEX IF NOT EXISTS idx_pkm_periods_year ON pkm_periods (year);

-- PKM_SCHEMES -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pkm_schemes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(30) NOT NULL UNIQUE,   -- PKM-K, PKM-PI, PKM-PM, ...
    name        VARCHAR(150) NOT NULL,
    description TEXT,
    min_members INT NOT NULL DEFAULT 3 CHECK (min_members >= 1),
    max_members INT NOT NULL DEFAULT 5 CHECK (max_members >= min_members),
    is_active   BOOLEAN NOT NULL DEFAULT TRUE
);

-- PKM_STAGES ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pkm_stages (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    period_id   UUID NOT NULL REFERENCES pkm_periods (id) ON DELETE CASCADE,
    name        VARCHAR(150) NOT NULL,
    stage_order INT NOT NULL DEFAULT 0,
    start_date  DATE,
    end_date    DATE,
    status      VARCHAR(30) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'active', 'completed', 'cancelled')),
    description TEXT,
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
    UNIQUE (period_id, stage_order),
    -- Target FK komposit dari proposals.current_stage_id agar tahapan aktif
    -- wajib berasal dari periode yang sama dengan proposal.
    UNIQUE (id, period_id)
);
CREATE INDEX IF NOT EXISTS idx_pkm_stages_period_id ON pkm_stages (period_id);

-- ============================================================================
-- 3. TIM PKM
-- ============================================================================

-- TEAMS -----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS teams (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    period_id  UUID NOT NULL REFERENCES pkm_periods (id) ON DELETE RESTRICT,
    leader_id  UUID NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    name       VARCHAR(150) NOT NULL,
    status     VARCHAR(30) NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'formed', 'submitted', 'disbanded')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Target FK komposit dari proposals (menjamin tim & proposal seperiode).
    UNIQUE (id, period_id)
);
CREATE INDEX IF NOT EXISTS idx_teams_period_id ON teams (period_id);
CREATE INDEX IF NOT EXISTS idx_teams_leader_id ON teams (leader_id);

-- TEAM_MEMBERS ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS team_members (
    team_id           UUID NOT NULL REFERENCES teams (id) ON DELETE CASCADE,
    student_id        UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    member_role       VARCHAR(30) NOT NULL DEFAULT 'member'
        CHECK (member_role IN ('leader', 'member')),
    invitation_status VARCHAR(30) NOT NULL DEFAULT 'pending'
        CHECK (invitation_status IN ('pending', 'accepted', 'rejected', 'removed')),
    joined_at         TIMESTAMPTZ,
    PRIMARY KEY (team_id, student_id)
);
CREATE INDEX IF NOT EXISTS idx_team_members_student_id ON team_members (student_id);

-- TEAM_INVITATIONS ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS team_invitations (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    team_id      UUID NOT NULL REFERENCES teams (id) ON DELETE CASCADE,
    sender_id    UUID NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    recipient_id UUID NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    message      TEXT,
    status       VARCHAR(30) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'accepted', 'rejected', 'cancelled', 'expired')),
    responded_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_team_invitations_team_id ON team_invitations (team_id);
CREATE INDEX IF NOT EXISTS idx_team_invitations_recipient_id ON team_invitations (recipient_id);

-- ============================================================================
-- 4. PROPOSAL & DOKUMEN
-- ============================================================================

-- PROPOSALS -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS proposals (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    team_id          UUID NOT NULL,
    scheme_id        BIGINT NOT NULL REFERENCES pkm_schemes (id) ON DELETE RESTRICT,
    period_id        UUID NOT NULL REFERENCES pkm_periods (id) ON DELETE RESTRICT,
    title            VARCHAR(255) NOT NULL,
    abstract         TEXT,
    keywords         TEXT,
    status           VARCHAR(30) NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'submitted', 'under_review', 'revision',
                          'approved', 'rejected', 'funded', 'completed')),
    current_stage_id UUID,
    is_funded        BOOLEAN NOT NULL DEFAULT FALSE,
    submitted_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Tim proposal harus berasal dari periode yang sama dengan proposal.
    CONSTRAINT fk_proposals_team_period
        FOREIGN KEY (team_id, period_id)
        REFERENCES teams (id, period_id) ON DELETE CASCADE,
    -- Tahapan aktif harus milik periode proposal (tidak boleh lintas periode).
    -- MATCH SIMPLE: bila current_stage_id NULL, constraint otomatis dilewati.
    CONSTRAINT fk_proposals_stage_period
        FOREIGN KEY (current_stage_id, period_id)
        REFERENCES pkm_stages (id, period_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_proposals_team_id ON proposals (team_id);
CREATE INDEX IF NOT EXISTS idx_proposals_scheme_id ON proposals (scheme_id);
CREATE INDEX IF NOT EXISTS idx_proposals_period_id ON proposals (period_id);
CREATE INDEX IF NOT EXISTS idx_proposals_status ON proposals (status);

-- PROPOSAL_DOCUMENTS ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS proposal_documents (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    proposal_id    UUID NOT NULL REFERENCES proposals (id) ON DELETE CASCADE,
    version_number INT NOT NULL DEFAULT 1 CHECK (version_number >= 1),
    file_name      VARCHAR(255) NOT NULL,
    file_url       TEXT NOT NULL,
    uploaded_by    UUID REFERENCES users (id) ON DELETE SET NULL,
    change_notes   TEXT,
    uploaded_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (proposal_id, version_number)
);
CREATE INDEX IF NOT EXISTS idx_proposal_documents_proposal_id ON proposal_documents (proposal_id);

-- SUPERVISOR_REQUESTS ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS supervisor_requests (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    proposal_id      UUID NOT NULL REFERENCES proposals (id) ON DELETE CASCADE,
    lecturer_id      UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    requested_by     UUID REFERENCES users (id) ON DELETE SET NULL,
    request_message  TEXT,
    status           VARCHAR(30) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'accepted', 'rejected', 'cancelled')),
    response_message TEXT,
    responded_at     TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_supervisor_requests_proposal_id ON supervisor_requests (proposal_id);
CREATE INDEX IF NOT EXISTS idx_supervisor_requests_lecturer_id ON supervisor_requests (lecturer_id);

-- PROPOSAL_SUPERVISORS --------------------------------------------------------
CREATE TABLE IF NOT EXISTS proposal_supervisors (
    proposal_id UUID NOT NULL REFERENCES proposals (id) ON DELETE CASCADE,
    lecturer_id UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    is_primary  BOOLEAN NOT NULL DEFAULT FALSE,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (proposal_id, lecturer_id)
);
CREATE INDEX IF NOT EXISTS idx_proposal_supervisors_lecturer_id ON proposal_supervisors (lecturer_id);

-- GUIDANCE_SESSIONS -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS guidance_sessions (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    proposal_id  UUID NOT NULL REFERENCES proposals (id) ON DELETE CASCADE,
    lecturer_id  UUID REFERENCES users (id) ON DELETE SET NULL,
    scheduled_at TIMESTAMPTZ NOT NULL,
    location     VARCHAR(255),
    meeting_url  TEXT,
    status       VARCHAR(30) NOT NULL DEFAULT 'scheduled'
        CHECK (status IN ('scheduled', 'completed', 'cancelled', 'rescheduled')),
    agenda       TEXT,
    meeting_notes TEXT
);
CREATE INDEX IF NOT EXISTS idx_guidance_sessions_proposal_id ON guidance_sessions (proposal_id);

-- PROPOSAL_FEEDBACK -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS proposal_feedback (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    proposal_id       UUID NOT NULL REFERENCES proposals (id) ON DELETE CASCADE,
    document_id       UUID REFERENCES proposal_documents (id) ON DELETE SET NULL,
    author_id         UUID REFERENCES users (id) ON DELETE SET NULL,
    feedback_type     VARCHAR(30) NOT NULL DEFAULT 'comment'
        CHECK (feedback_type IN ('comment', 'revision', 'approval', 'rejection')),
    comment           TEXT NOT NULL,
    requires_revision BOOLEAN NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_proposal_feedback_proposal_id ON proposal_feedback (proposal_id);

-- ============================================================================
-- 5. REVIEW & PENILAIAN
-- ============================================================================

-- REVIEW_CRITERIA -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS review_criteria (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scheme_id   BIGINT NOT NULL REFERENCES pkm_schemes (id) ON DELETE CASCADE,
    name        VARCHAR(150) NOT NULL,
    description TEXT,
    max_score   NUMERIC(6, 2) NOT NULL DEFAULT 100 CHECK (max_score >= 0),
    weight      NUMERIC(5, 2) NOT NULL DEFAULT 1  CHECK (weight >= 0)
);
CREATE INDEX IF NOT EXISTS idx_review_criteria_scheme_id ON review_criteria (scheme_id);

-- REVIEW_ASSIGNMENTS ----------------------------------------------------------
CREATE TABLE IF NOT EXISTS review_assignments (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    proposal_id     UUID NOT NULL REFERENCES proposals (id) ON DELETE CASCADE,
    reviewer_id     UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    assigned_by     UUID REFERENCES users (id) ON DELETE SET NULL,
    status          VARCHAR(30) NOT NULL DEFAULT 'assigned'
        CHECK (status IN ('assigned', 'in_progress', 'completed', 'cancelled')),
    review_deadline DATE,
    assigned_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_review_assignments_proposal_id ON review_assignments (proposal_id);
CREATE INDEX IF NOT EXISTS idx_review_assignments_reviewer_id ON review_assignments (reviewer_id);

-- REVIEWS ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS reviews (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    assignment_id   UUID NOT NULL UNIQUE REFERENCES review_assignments (id) ON DELETE CASCADE,
    total_score     NUMERIC(6, 2) CHECK (total_score >= 0),
    strengths       TEXT,
    weaknesses      TEXT,
    comments        TEXT,
    recommendation  VARCHAR(30)
        CHECK (recommendation IN ('funded', 'revision', 'rejected', 'accepted')),
    review_status   VARCHAR(30) NOT NULL DEFAULT 'draft'
        CHECK (review_status IN ('draft', 'submitted', 'finalized')),
    submitted_at    TIMESTAMPTZ
);

-- REVIEW_SCORES ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS review_scores (
    review_id    UUID   NOT NULL REFERENCES reviews (id) ON DELETE CASCADE,
    criterion_id BIGINT NOT NULL REFERENCES review_criteria (id) ON DELETE CASCADE,
    score        NUMERIC(6, 2) NOT NULL DEFAULT 0 CHECK (score >= 0),
    comment      TEXT,
    PRIMARY KEY (review_id, criterion_id)
);
CREATE INDEX IF NOT EXISTS idx_review_scores_criterion_id ON review_scores (criterion_id);

-- ============================================================================
-- 6. LOGBOOK KEGIATAN
-- ============================================================================

-- LOGBOOK_ENTRIES -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS logbook_entries (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    proposal_id         UUID NOT NULL REFERENCES proposals (id) ON DELETE CASCADE,
    student_id          UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    activity_date       DATE NOT NULL,
    title               VARCHAR(255) NOT NULL,
    activity_description TEXT,
    progress_result     TEXT,
    obstacle            TEXT,
    next_plan           TEXT,
    attachment_url      TEXT,
    verification_status VARCHAR(30) NOT NULL DEFAULT 'pending'
        CHECK (verification_status IN ('pending', 'approved', 'revision', 'rejected')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_logbook_entries_proposal_id ON logbook_entries (proposal_id);
CREATE INDEX IF NOT EXISTS idx_logbook_entries_student_id ON logbook_entries (student_id);

-- LOGBOOK_COMMENTS ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS logbook_comments (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    logbook_id UUID NOT NULL REFERENCES logbook_entries (id) ON DELETE CASCADE,
    author_id  UUID REFERENCES users (id) ON DELETE SET NULL,
    comment    TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_logbook_comments_logbook_id ON logbook_comments (logbook_id);

-- ============================================================================
-- 7. ANALISIS AI
-- ============================================================================

CREATE TABLE IF NOT EXISTS ai_analyses (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    requested_by     UUID REFERENCES users (id) ON DELETE SET NULL,
    proposal_id      UUID REFERENCES proposals (id) ON DELETE CASCADE,
    analysis_type    VARCHAR(50) NOT NULL,   -- proposal_review | idea_scoring | similarity | ...
    input_text       TEXT,
    output_text      TEXT,
    confidence_score NUMERIC(5, 4) CHECK (confidence_score >= 0 AND confidence_score <= 1),
    model_name       VARCHAR(100),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ai_analyses_proposal_id ON ai_analyses (proposal_id);
CREATE INDEX IF NOT EXISTS idx_ai_analyses_requested_by ON ai_analyses (requested_by);

-- ============================================================================
-- 8. KONTEN / CMS
-- ============================================================================

-- CONTENT_POSTS (berita/artikel) ---------------------------------------------
CREATE TABLE IF NOT EXISTS content_posts (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    author_id       UUID REFERENCES users (id) ON DELETE SET NULL,
    content_type    VARCHAR(30) NOT NULL DEFAULT 'news'
        CHECK (content_type IN ('news', 'article', 'announcement', 'page')),
    title           VARCHAR(255) NOT NULL,
    slug            VARCHAR(255) NOT NULL UNIQUE,
    summary         TEXT,
    content         TEXT,
    cover_image_url TEXT,
    status          VARCHAR(30) NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'published', 'archived')),
    published_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_content_posts_status ON content_posts (status);
CREATE INDEX IF NOT EXISTS idx_content_posts_content_type ON content_posts (content_type);

-- CONTENT_MEDIA (video & galeri) ---------------------------------------------
-- Tabel tambahan terintegrasi: ERD hanya memuat CONTENT_POSTS, sedangkan fitur
-- lama menyimpan berita + video + galeri dalam satu tabel `contents`.
-- Berita pindah ke content_posts; video/galeri ditampung di sini.
CREATE TABLE IF NOT EXISTS content_media (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    author_id     UUID REFERENCES users (id) ON DELETE SET NULL,
    media_type    VARCHAR(30) NOT NULL CHECK (media_type IN ('video', 'gallery')),
    title         VARCHAR(255) NOT NULL,
    description   TEXT,
    media_url     TEXT,     -- URL foto (galeri) atau tautan video
    thumbnail_url TEXT,
    color         VARCHAR(30) DEFAULT 'gold',
    status        VARCHAR(30) NOT NULL DEFAULT 'published'
        CHECK (status IN ('draft', 'published', 'archived')),
    sort_order    INT NOT NULL DEFAULT 0,
    published_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_content_media_media_type ON content_media (media_type);

-- GUIDELINES (pedoman/panduan) -----------------------------------------------
CREATE TABLE IF NOT EXISTS guidelines (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    period_id      UUID REFERENCES pkm_periods (id) ON DELETE SET NULL,
    title          VARCHAR(255) NOT NULL,
    file_url       TEXT NOT NULL,
    source         VARCHAR(150),   -- asal dokumen, mis. "SIMBELMAWA" (dari pedoman lama)
    note           TEXT,           -- keterangan tambahan (dari pedoman lama)
    version_number INT NOT NULL DEFAULT 1 CHECK (version_number >= 1),
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    published_at   TIMESTAMPTZ,
    UNIQUE (title, version_number)
);
CREATE INDEX IF NOT EXISTS idx_guidelines_period_id ON guidelines (period_id);

-- NOTIFICATIONS ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notifications (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id           UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    notification_type VARCHAR(50) NOT NULL,   -- invitation | status_change | feedback | ...
    title             VARCHAR(255) NOT NULL,
    message           TEXT,
    target_url        TEXT,
    is_read           BOOLEAN NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications (user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications (user_id, is_read);

-- ============================================================================
-- 9. TABEL TAMBAHAN TERINTEGRASI (fitur lama tanpa padanan di ERD)
--    Tabel berikut resmi bagian dari skema (bukan tabel sementara), agar fitur
--    Masukan, Kontak, dan Statistik yang sudah berjalan tetap punya wadah.
-- ============================================================================

-- FEEDBACKS (Kritik & Saran + pesan Kontak) -----------------------------------
-- Menggantikan tabel lama `feedbacks`.
CREATE TABLE IF NOT EXISTS feedbacks (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind       VARCHAR(30) NOT NULL CHECK (kind IN ('saran', 'kontak')),
    name       VARCHAR(150),
    email      VARCHAR(255),
    message    TEXT NOT NULL,
    is_read    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_feedbacks_kind ON feedbacks (kind);

-- CONTACT_INFOS (baris tunggal id = 1) ----------------------------------------
-- Menggantikan tabel lama `contact_infos`.
CREATE TABLE IF NOT EXISTS contact_infos (
    id         BIGINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    address    TEXT,
    email      VARCHAR(255),
    phone      VARCHAR(50),
    whatsapp   VARCHAR(50),
    instagram  VARCHAR(150),
    facebook   VARCHAR(150),
    map_embed  TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- 10. VIEW: statistik usulan per skema (menggantikan tabel `scheme_stats`)
-- ============================================================================
-- Keputusan: statistik skema murni TURUNAN dari proposals — tidak ada tabel
-- `scheme_stats` dan tidak ada input manual. Endpoint admin terkait dihapus.
-- Statistik jumlah usulan kini dihitung dari PROPOSALS, bukan tabel tersendiri.
CREATE OR REPLACE VIEW v_scheme_stats AS
SELECT
    s.id     AS scheme_id,
    s.code   AS scheme,
    s.name   AS scheme_name,
    COUNT(p.id) FILTER (WHERE p.status <> 'draft') AS proposal_count,
    COUNT(p.id) FILTER (WHERE p.is_funded)         AS funded_count
FROM pkm_schemes s
LEFT JOIN proposals p ON p.scheme_id = s.id
GROUP BY s.id, s.code, s.name
ORDER BY s.id;

-- ============================================================================
-- 11. SEED DASAR: roles & skema PKM
-- ============================================================================
INSERT INTO roles (code, name, description) VALUES
    ('admin',     'Administrator',  'Pengelola penuh sistem PKM Center'),
    ('mahasiswa', 'Mahasiswa',      'Pengusul/anggota tim PKM'),
    ('dosen',     'Dosen',          'Dosen pembimbing / pengusul'),
    ('reviewer',  'Reviewer',       'Penilai proposal PKM'),
    ('pimpinan',  'Pimpinan',       'Pejabat yang melihat rekap/laporan')
ON CONFLICT (code) DO NOTHING;

INSERT INTO pkm_schemes (code, name, description, min_members, max_members) VALUES
    ('PKM-K',   'PKM Kewirausahaan',                 'Pengembangan usaha/kewirausahaan mahasiswa.', 3, 5),
    ('PKM-PI',  'PKM Penerapan Iptek',               'Penerapan ilmu pengetahuan & teknologi.', 3, 5),
    ('PKM-PM',  'PKM Pengabdian kepada Masyarakat',  'Program pemberdayaan masyarakat.', 3, 5),
    ('PKM-KC',  'PKM Karsa Cipta',                   'Rancang bangun purwarupa/karya inovatif.', 3, 5),
    ('PKM-GFT', 'PKM Gagasan Futuristik Tertulis',   'Gagasan futuristik dalam bentuk tulisan.', 3, 5),
    ('PKM-KI',  'PKM Karya Inovatif',                'Karya inovatif yang aplikatif.', 3, 5),
    ('PKM-AI',  'PKM Artikel Ilmiah',                'Artikel ilmiah hasil kegiatan.', 3, 5),
    ('PKM-RE',  'PKM Riset Eksakta',                 'Penelitian bidang eksakta.', 3, 5),
    ('PKM-RSH', 'PKM Riset Sosial Humaniora',        'Penelitian bidang sosial humaniora.', 3, 5)
ON CONFLICT (code) DO NOTHING;

COMMIT;

-- ============================================================================
-- SELESAI. Verifikasi cepat:
--   SELECT table_name FROM information_schema.tables
--     WHERE table_schema = 'public' ORDER BY table_name;
--   SELECT * FROM v_scheme_stats;
-- ============================================================================
