import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const api = import.meta.env.VITE_API_URL || 'http://localhost:8081/api'
const news = [
  { id: 1, category: 'Pengumuman', date: '12 September 2026', title: 'Pendaftaran pendampingan proposal PKM segera dibuka', excerpt: 'Siapkan ide terbaikmu dan ikuti sesi pendampingan awal bersama PKM Center.', color: 'gold' },
  { id: 2, category: 'Kegiatan', date: '05 September 2026', title: 'Meracik gagasan menjadi proposal yang berdampak', excerpt: 'Catatan dari kelas intensif pengembangan proposal bagi mahasiswa Unila.', color: 'blue' },
  { id: 3, category: 'Prestasi', date: '28 Agustus 2026', title: 'Merayakan karya dan kolaborasi mahasiswa Unila', excerpt: 'Ruang apresiasi untuk perjalanan tim PKM dari kampus ke masyarakat.', color: 'red' },
  { id: 4, category: 'Info PKM', date: '20 Agustus 2026', title: 'Mengenal lintasan skema Program Kreativitas Mahasiswa', excerpt: 'Panduan awal memilih skema yang sesuai dengan pertanyaan dan gagasanmu.', color: 'green' },
  { id: 5, category: 'Kegiatan', date: '14 Agustus 2026', title: 'Klinik proposal: dari riset ke aksi nyata', excerpt: 'Belajar menyusun alur proposal yang kuat, jernih, dan mudah dipahami.', color: 'gold' },
  { id: 6, category: 'Pengumuman', date: '08 Agustus 2026', title: 'Agenda PKM Center untuk semester ini', excerpt: 'Simpan tanggal penting untuk pelatihan, klinik, dan sesi konsultasi.', color: 'blue' },
]
const gallery = [['Kelas pengembangan ide','gold'],['Diskusi tim lintas disiplin','blue'],['Presentasi karya mahasiswa','red'],['Pendampingan proposal','green'],['Ruang kolaborasi PKM','blue'],['Perayaan proses dan karya','gold'],['Belajar bersama mentor','red'],['Dari kampus untuk masyarakat','green']]
const videos = [['Mengenal PKM Center','Tentang ruang tumbuh ide dan karya mahasiswa.','gold'],['Kiat memulai proposal PKM','Langkah pertama dari gagasan menuju proposal.','blue'],['Cerita dari tim PKM','Catatan proses, kolaborasi, dan pembelajaran.','red']]

function Brand(){return <a className="brand" href="#beranda" aria-label="PKM Center Universitas Lampung"><img className="brand-logo" src="/logo-pkm-center.png" alt="Logo PKM Center Universitas Lampung"/><span>PKM <i>Center</i><small>UNIVERSITAS LAMPUNG</small></span></a>}
function Header({user,onLogin,onLogout}){return <header><Brand/><nav><a href="#beranda">Beranda</a><a href="#berita">Berita</a><a href="#galeri">Galeri</a><a href="#tentang">Tentang</a></nav>{user?<button className="profile" onClick={onLogout}>{user.name.split(' ')[0]} <span>{user.role}</span></button>:<button className="login-trigger" onClick={onLogin}>Masuk <b>→</b></button>}</header>}
function Home(){return <main id="beranda"><section className="hero"><div className="hero-copy"><p className="eyebrow">RUANG TUMBUH IDE MAHASISWA</p><h1>Gagasan kecil.<br/><em>Dampak besar.</em></h1><p className="intro">PKM Center Unila adalah titik temu bagi rasa ingin tahu, riset yang berani, dan karya yang memberi arti.</p><div className="actions"><a className="button dark" href="#berita">Lihat kabar terbaru <b>↗</b></a><a className="text-link" href="#tentang">Kenali PKM <b>↓</b></a></div></div><div className="hero-art"><div className="sun"/><div className="arch arch-one"/><div className="arch arch-two"/><div className="orb orb-one"/><div className="orb orb-two"/><div className="note">IDE<br/>TUMBUH</div><p className="art-caption">UNILA<br/><i>CREATIVE<br/>ECOSYSTEM</i></p></div></section><section className="ticker"><span>BERPIKIR</span><b>✦</b><span>BERKARYA</span><b>✦</b><span>BERDAMPAK</span><b>✦</b><span>BERSAMA UNILA</span></section><section className="journey" id="tentang"><div><p className="eyebrow">SATU IDE, BANYAK KEMUNGKINAN</p><h2>Temukan lintasanmu.</h2></div><div className="path-grid"><article><span>01</span><h3>Jelajahi</h3><p>Temukan bentuk PKM yang paling dekat dengan kegelisahanmu.</p></article><article><span>02</span><h3>Racik</h3><p>Ubah pertanyaan menjadi proposal yang kuat dan terarah.</p></article><article><span>03</span><h3>Wujudkan</h3><p>Bawa gagasanmu keluar kelas untuk menciptakan perubahan.</p></article></div></section></main>}
function PageIntro({eyebrow,title,copy}){return <section className="page-intro"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p></section>}
function NewsIndex(){const [page,setPage]=useState(1),shown=news.slice((page-1)*3,page*3);return <main><PageIntro eyebrow="KABAR DARI PKM CENTER" title={<>Cerita yang terus<br/><em>bertumbuh.</em></>} copy="Pengumuman, kegiatan, dan catatan perjalanan karya mahasiswa PKM Unila."/><section className="news-grid">{shown.map(item=><a className={`news-card ${item.color}`} href={`#berita/${item.id}`} key={item.id}><div className="news-visual"><span>{item.category}</span><b>↗</b></div><p className="card-meta">{item.date} · {item.category}</p><h2>{item.title}</h2><p>{item.excerpt}</p><span className="read-more">Baca selengkapnya →</span></a>)}</section><nav className="pagination" aria-label="Pagination berita">{[1,2].map(number=><button key={number} className={page===number?'active':''} onClick={()=>setPage(number)}>{number}</button>)}</nav></main>}
function NewsDetail({id}){const item=news.find(article=>article.id===Number(id))||news[0];return <main><article className="article-detail"><a className="back-link" href="#berita">← Semua berita</a><p className="eyebrow">{item.category} · {item.date}</p><h1>{item.title}</h1><div className={`article-image ${item.color}`}><span>PKM CENTER<br/>UNIVERSITAS LAMPUNG</span></div><p className="lead">{item.excerpt}</p><p>Halaman ini adalah format artikel yang siap dihubungkan ke data berita dari admin. Isi lengkap, gambar utama, penulis, dan kategori dapat dikelola pada sistem konten pada tahap berikutnya.</p><p>Untuk sementara, materi di sini digunakan sebagai contoh tampilan agar pembaca dapat melihat alur dari daftar berita menuju detail artikel secara utuh.</p></article></main>}
function Gallery(){const [selected,setSelected]=useState(null);return <main><PageIntro eyebrow="DOKUMENTASI KEGIATAN" title={<>Ruang, proses,<br/><em>dan perjumpaan.</em></>} copy="Potongan momen dari perjalanan belajar, berkolaborasi, dan berkarya bersama PKM Center."/><section className="video-section"><div className="section-heading"><p className="eyebrow">VIDEO KEGIATAN</p><h2>Putar kembali prosesnya.</h2></div><div className="video-grid">{videos.map(([title,description,color])=><article className={`video-card ${color}`} key={title}><button className="play" aria-label={`Putar ${title}`}>▶</button><div><p className="card-meta">VIDEO · SEGERA HADIR</p><h3>{title}</h3><p>{description}</p></div></article>)}</div><p className="content-note">Area video siap menerima tautan YouTube atau berkas video dari pengelola.</p></section><section className="gallery-section" id="galeri"><div className="section-heading"><p className="eyebrow">GALERI FOTO</p><h2>Melihat ide bekerja.</h2></div><div className="gallery-grid">{gallery.map(([title,color],index)=><button className={`gallery-item ${color}`} onClick={()=>setSelected({title,color,index})} key={title}><span>{String(index+1).padStart(2,'0')}</span><strong>{title}</strong><b>↗</b></button>)}</div></section>{selected&&<div className="lightbox" onMouseDown={()=>setSelected(null)}><section onMouseDown={event=>event.stopPropagation()} className={`lightbox-content ${selected.color}`}><button className="close" onClick={()=>setSelected(null)}>×</button><span>GALERI PKM CENTER · {String(selected.index+1).padStart(2,'0')}</span><h2>{selected.title}</h2><p>Area foto ukuran penuh. Ganti blok ini dengan dokumentasi kegiatan asli melalui admin.</p></section></div>}</main>}
function LoginModal({close,complete}){const [form,setForm]=useState({email:'',password:''}),[state,setState]=useState({loading:false,error:''});const login=async event=>{event.preventDefault();setState({loading:true,error:''});try{const response=await fetch(`${api}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}),result=await response.json();if(!response.ok)throw new Error(result.message);localStorage.setItem('pkm_user',JSON.stringify(result.user));localStorage.setItem('pkm_token',result.token);complete(result.user);close()}catch(error){setState({loading:false,error:error.message})}};return <div className="modal-backdrop" onMouseDown={close}><section className="modal" onMouseDown={event=>event.stopPropagation()}><button className="close" onClick={close}>×</button><p className="eyebrow">SELAMAT DATANG KEMBALI</p><h2>Masuk ke ruangmu.</h2><form onSubmit={login}><label>Email<input type="email" placeholder="nama@pkm.unila.ac.id" value={form.email} onChange={event=>setForm({...form,email:event.target.value})} required/></label><label>Kata sandi<input type="password" placeholder="••••••••" value={form.password} onChange={event=>setForm({...form,password:event.target.value})} required/></label>{state.error&&<p className="error">{state.error}</p>}<button className="button dark" disabled={state.loading}>{state.loading?'Memeriksa…':'Masuk ke PKM Center'} <b>→</b></button></form><p className="hint">Akun demo: admin@pkm.unila.ac.id / admin123</p></section></div>}
function App(){const [hash,setHash]=useState(window.location.hash||'#beranda'),[modal,setModal]=useState(false),[user,setUser]=useState(JSON.parse(localStorage.getItem('pkm_user')||'null'));useEffect(()=>{const listen=()=>setHash(window.location.hash||'#beranda');window.addEventListener('hashchange',listen);return()=>window.removeEventListener('hashchange',listen)},[]);const logout=()=>{localStorage.clear();setUser(null)},route=hash.replace('#','').split('/');const view=route[0]==='berita'?(route[1]?<NewsDetail id={route[1]}/>:<NewsIndex/>):route[0]==='galeri'?<Gallery/>:<Home/>;return <><Header user={user} onLogin={()=>setModal(true)} onLogout={logout}/>{view}<footer><span>PKM CENTER · UNIVERSITAS LAMPUNG</span><span>2026 — Dibuat untuk ide yang tak mau diam.</span></footer>{modal&&<LoginModal close={()=>setModal(false)} complete={setUser}/>}</>}
createRoot(document.getElementById('root')).render(<App />)
